/**
 * @packageDocumentation
 * @module api.functional.users.me.role
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";
import TSON from "typescript-json";

import type { IUserUsecase } from "../../../../../../src/api/user/application/port/user.usecase.port";

/**
 * 내 권한 수정 API
 * 
 * @tag users
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param body 변경할 권한 정보를 포함
 * @returns 아무것도 반환하지 않습니다.
 * @throw 401 로그인이 필요합니다.
 * 
 * @controller UserController.setRole()
 * @path PATCH /users/me/role
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function setRole
    (
        connection: IConnection,
        body: IUserUsecase.SetRoleBody
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        setRole.ENCRYPTED,
        setRole.METHOD,
        setRole.path(),
        body,
        setRole.stringify
    );
}
export namespace setRole
{
    export type Input = IUserUsecase.SetRoleBody;

    export const METHOD = "PATCH" as const;
    export const PATH: string = "/users/me/role";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/users/me/role`;
    }
    export const stringify = (input: Input) => TSON.stringify(input);
}