/**
 * @packageDocumentation
 * @module api.functional.users.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

import type { IUserAggregate } from "./../../../../interface/user/domain/index";

export * as role from "./role";

/**
 * 내 프로필 보기 API
 * 
 * @tag users
 * @returns 계정 정보와 사용자 권한 정보 등을 전달
 * @throw 401 로그인이 필요합니다.
 * 
 * @controller UserController.me()
 * @path GET /users/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function me
    (
        connection: IConnection
    ): Promise<me.Output>
{
    return Fetcher.fetch
    (
        connection,
        me.ENCRYPTED,
        me.METHOD,
        me.path()
    );
}
export namespace me
{
    export type Output = IUserAggregate.Public;

    export const METHOD = "GET" as const;
    export const PATH: string = "/users/me";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/users/me`;
    }
}

/**
 * user delete API
 * 
 * @tag users
 * 
 * @controller UserController.remove()
 * @path DELETE /users/me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function remove
    (
        connection: IConnection
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        remove.ENCRYPTED,
        remove.METHOD,
        remove.path()
    );
}
export namespace remove
{

    export const METHOD = "DELETE" as const;
    export const PATH: string = "/users/me";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/users/me`;
    }
}